[package]
name = "traitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.11.0"
elf = "0.7.2"
queues = "1.1.0"
iced-x86 = "1.18.0"
